"""
Type stubs for the compiled Rust/PyO3 extension module `_aranya_prime`.
These are used by Pyright / Pylance for static analysis only.
"""

from typing import Tuple
import numpy as np
from numpy.typing import ArrayLike, NDArray

# ── Polynomials ────────────────────────────────────────────────────────────────
def prime_poly(x: ArrayLike) -> NDArray[np.float64]: ...

# ── Trigonometry ──────────────────────────────────────────────────────────────
def prime_sin(x: ArrayLike) -> NDArray[np.float64]: ...
def prime_cos(x: ArrayLike) -> NDArray[np.float64]: ...
def prime_tan(x: ArrayLike) -> NDArray[np.float64]: ...

# ── Element-wise Array Operations ─────────────────────────────────────────────
def prime_math_sum(x: ArrayLike, y: ArrayLike) -> NDArray[np.float64]: ...
def prime_sub(x: ArrayLike, y: ArrayLike) -> NDArray[np.float64]: ...
def prime_mul(x: ArrayLike, y: ArrayLike) -> NDArray[np.float64]: ...
def prime_div(x: ArrayLike, y: ArrayLike) -> NDArray[np.float64]: ...

# ── Linear Algebra (1D) ───────────────────────────────────────────────────────
def prime_dot(x: ArrayLike, y: ArrayLike) -> float: ...
def prime_mag(x: ArrayLike) -> float: ...
def prime_normalize(x: ArrayLike) -> NDArray[np.float64]: ...

# ── Linear Algebra (2D) ───────────────────────────────────────────────────────
def prime_matmul(A: ArrayLike, B: ArrayLike) -> NDArray[np.float64]: ...
def prime_normalize_batch(X: ArrayLike) -> NDArray[np.float64]: ...

# ── Statistics & Norms ────────────────────────────────────────────────────────
def prime_sum(x: ArrayLike) -> float: ...
def prime_mean(x: ArrayLike) -> float: ...
def prime_std(x: ArrayLike) -> float: ...
def prime_clip(x: ArrayLike, min_val: float, max_val: float) -> NDArray[np.float64]: ...
def prime_l2_norm(x: ArrayLike) -> float: ...
def prime_linf_norm(x: ArrayLike) -> float: ...

# ── Transforms ────────────────────────────────────────────────────────────────
def prime_scale(x: ArrayLike, s: float) -> NDArray[np.float64]: ...
def prime_rotate_2d(
    x: ArrayLike, y: ArrayLike, angle_rad: float
) -> Tuple[NDArray[np.float64], NDArray[np.float64]]: ...

# ── Signal Processing ─────────────────────────────────────────────────────────
def prime_convolve(signal: ArrayLike, kernel: ArrayLike) -> NDArray[np.float64]: ...
def prime_fft(x: ArrayLike) -> Tuple[NDArray[np.float64], NDArray[np.float64]]: ...
def prime_ifft(re: ArrayLike, im: ArrayLike) -> NDArray[np.float64]: ...
def prime_dct(x: ArrayLike) -> NDArray[np.float64]: ...
def prime_wavelet_transform(x: ArrayLike) -> NDArray[np.float64]: ...

# ── Single-precision (f32) variants ───────────────────────────────────────────
def prime_sin_f32(x: ArrayLike) -> NDArray[np.float32]: ...
def prime_cos_f32(x: ArrayLike) -> NDArray[np.float32]: ...
def prime_tan_f32(x: ArrayLike) -> NDArray[np.float32]: ...
def prime_dot_f32(x: ArrayLike, y: ArrayLike) -> float: ...
def prime_matmul_f32(A: ArrayLike, B: ArrayLike) -> NDArray[np.float32]: ...
def prime_rotate_2d_f32(x: ArrayLike, y: ArrayLike, angle_rad: float) -> Tuple[NDArray[np.float32], NDArray[np.float32]]: ...

# ── Streaming / Chunked ───────────────────────────────────────────────────────
def prime_chunked_sin(x: ArrayLike, chunk_size: int) -> NDArray[np.float64]: ...
def prime_chunked_rotate_2d(x: ArrayLike, y: ArrayLike, angle_rad: float, chunk_size: int) -> Tuple[NDArray[np.float64], NDArray[np.float64]]: ...

# ── BLAS / LAPACK ─────────────────────────────────────────────────────────────
def prime_blas_dot(x: ArrayLike, y: ArrayLike) -> float: ...
def prime_blas_matmul(A: ArrayLike, B: ArrayLike) -> NDArray[np.float64]: ...
def prime_svd(A: ArrayLike) -> Tuple[NDArray[np.float64], NDArray[np.float64], NDArray[np.float64]]: ...
